### ISSUE TITLE
yeelink.light.ceiling10 unterer Weißwert

### ISSUE THREAD

**Issue by tkaufmann** [Nall-chan/Yeelight#8]
(Zumindest) bei der yeelink.light.ceiling10 ist der untere Weißwert 2700. Gemäß Doku müsste auch 1700 möglich sein, das führt aber zu einer Fehlermeldung: 

````
<b>Warning</b>:  count(): Parameter must be an array or an object that implements Countable in <b>/var/lib/symcon/modules/.store/de.nall.chan.yeelight/YeelightDevice/module.php</b> on line <b>1150</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Cannot use object of type Yeelight\YeelightRPCException as array in /var/lib/symcon/modules/.store/de.nall.chan.yeelight/YeelightDevice/module.php:1151
Stack trace:
#0 /var/lib/symcon/modules/.store/de.nall.chan.yeelight/YeelightDevice/module.php(372): YeelightDevice-&gt;Send(Object(Yeelight\YeelightRPC_Data))
#1 /var/lib/symcon/scripts/__generated.inc.php(1075): YeelightDevice-&gt;SetWhiteSmooth(2699, 500)
#2 /var/lib/symcon/scripts/50462.ips.php(13): Yeelight_SetWhiteSmooth(22422, 2699, 500)
#3 {main}
  thrown in <b>/var/lib/symcon/modules/.store/de.nall.chan.yeelight/YeelightDevice/module.php</b> on line <b>1151</b><br />
````

**Comment by Nall-chan** [comment]
Du musst schon ein Debug der Instanz Anhängen von dem (Schalt) Vorgang.
Ohne den Debug Dump kann ich das nicht nachstellen.

**Comment by tkaufmann** [comment]
Wie kann ich den erzeugen?

**Comment by Nall-chan** [comment]
Wenn der Fehler in der aktuellen Version noch auftritt, bitte im Forum melden.
https://community.symcon.de/t/modul-xiaomi-yeelight-color-bulb/45887
